---
- name: Install Postgresql 12
  ansible.builtin.apt:
    name: postgresql-12
    state: present
    install_recommends: no

- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  shell: |
    /usr/bin/python3 /tmp/get-pip.py

- name: Install python-postgres packages packages
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary   
