---
- name: Download MS product repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb

- name: Install product repository
  apt: 
    deb: /tmp/packages-microsoft-prod.deb
  become: true

- name: Install MS requirements
  apt:
    name: apt-transport-https
    state: present
    update_cache: false
  become: true

- name: Install DOTNET SDK
  apt: 
    name: dotnet-sdk-6.0
    state: present
    update_cache: true
  become: true
