---
- name: Create app1 postgresql user
  community.postgresql.postgresql_user:
    name: app1
    password: app1
    state: present
  become: yes
  become_user: postgres

- name: Create app database
  community.postgresql.postgresql_db:
    name: app1
    owner: app1
    encoding: utf-8
    state: present
  become: yes
  become_user: postgres
