---
- name: Configure dev box
  hosts: hets
  roles:
    - dev_box
    - git
    - java
    - postgresql
    - role: node
      vars:
        node_version: 16 
        node_user: maly
    - app1
    
