---
- name: Create app directories
  become_user: webapp
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: 0777
  loop:
    - { path: /home/webapp/apps/jellyfin/config/ }
    - { path: /home/webapp/apps/jellyfin/music/ }
    - { path: /home/webapp/apps/nextcloud/ }
    - { path: /home/webapp/apps/caddy/}
    - { path: /home/webapp/apps/caddy/data}
    - { path: /home/webapp/apps/caddy/config}

- name: Copy docker-compose
  become_user: webapp
  ansible.builtin.copy:
    src: conf/docker-compose.yml
    dest: /home/webapp/apps

- name: Copy template for caddy configuration
  become_user: webapp
  ansible.builtin.template:
    src: conf/Caddyfile.j2
    dest: /home/webapp/apps/caddy/Caddyfile
    owner: webapp

- name: Create container
  become_user: webapp
  command: "docker-compose up -d"
  args: 
    chdir: /home/webapp/apps

- name: Restart containers
  become_user: webapp
  command: "docker-compose restart"
  args:
    chdir: /home/webapp/apps
