---
- name: Configure local computer
  hosts: do

  tasks:
    - name: Install FTP
      ansible.builtin.apt:
        name: vsftpd

    - name: Copy FTP configuration
      ansible.builtin.copy:
        src: conf/vsftpd.conf
        dest: /etc/vsftpd.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart vsftpd

    - name: Install vim
      ansible.builtin.apt:
        name: vim
        state: latest

    - name: Install Openjdk-8
      ansible.builtin.apt:
        name: openjdk-8-jdk
        state: latest
        install_recommends: no

    - name: Download docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /home/webapp/get-docker.sh

    - name: Install docker
      command: sh get-docker.sh
      args:
        chdir: /home/webapp

    - name: Add docker group to webapp user
      command: "usermod -aG docker webapp"

    - name: Install docker-compose requirements
      ansible.builtin.apt:
        pkg:
        - libffi-dev
        - libssl-dev
        - python3-dev
        - python3 
        - python3-pip

    - name: Install docker-compose
      command: pip3 install docker-compose

    - name: Install libseccomp2.4.4
      ansible.builtin.apt:
        deb: "http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb"
      tags:
      - arm

    - include: docker_playbook.yaml

  handlers:
    - name: Restart vsftpd
      become: yes
      ansible.builtin.service:
        name: vsftpd 
        state: restarted
