---
- name: Create new user
  ansible.builtin.user:
    name: maly
    shell: /bin/bash
    create_home: yes

- name: Allow sudo commands for user
  ansible.builtin.user:
    name: maly
    groups: sudo
    append: yes

- name: Remove password requirements for sudo for user
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%maly'
    line: '%maly ALL=(ALL) NOPASSWD: ALL'

- name: Allow new user ssh access
  ansible.builtin.authorized_key:
    user: maly
    state: present
    key: "{{ lookup('file', './id_dev_box_free.pub') }}"

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present